package test.entity;

// Generated Dec 1, 2015 12:57:27 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

import org.uncodeframework.core.common.entity.BaseEntity;
import org.uncodeframework.core.common.entity.LogicDeleteable;

/**
 * User generated by hbm2java
 */
@Entity
//@DynamicUpdate(true)
//@DynamicInsert(true)
@Table(name = "user", catalog = "uncodeframework")
public class User extends BaseEntity<String> implements LogicDeleteable {

	/** * @Fileds serialVersionUID :  */
	private static final long serialVersionUID = 1L;
	
	private String username;
	private Integer age;
	private Integer phone;
	private String email;
	
	/**
	 * 逻辑删除flag
	 */
	private Boolean deleted = Boolean.FALSE;

	public User() {
	}

	public User(String username, Integer age, Integer phone, String email) {
		this.username = username;
		this.age = age;
		this.phone = phone;
		this.email = email;
	}

	@Column(name = "username", length = 256)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "age")
	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	@Column(name = "phone")
	public Integer getPhone() {
		return this.phone;
	}

	public void setPhone(Integer phone) {
		this.phone = phone;
	}

	@Column(name = "email", length = 256)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Override
	public Boolean getDeleted() {
		return this.deleted;
	}

	@Override
	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}

	@Override
	public void markDeleted() {
		this.deleted = Boolean.TRUE;
	}

}
