package com.uncodeframework.wms.mapper;

import com.uncodeframework.wms.entity.Employeerole;
import java.util.List;

public interface EmployeeroleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeerole
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    int insert(Employeerole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeerole
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    List<Employeerole> selectAll();
}