package com.uncodeframework.wms.mapper;

import com.uncodeframework.wms.entity.Menurole;
import java.util.List;

public interface MenuroleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menurole
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    int insert(Menurole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menurole
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    List<Menurole> selectAll();
}