package com.uncodeframework.wms.mapper;

import com.uncodeframework.wms.entity.Sequence;
import java.util.List;

public interface SequenceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    int deleteByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    int insert(Sequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    Sequence selectByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    List<Sequence> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    int updateByPrimaryKey(Sequence record);
}