package com.uncodeframework.wms.entity;

import java.io.Serializable;

public class Employeerole implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeerole.EmployeeID
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    private String employeeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeerole.RoleID
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    private String roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table employeerole
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeerole.EmployeeID
     *
     * @return the value of employeerole.EmployeeID
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    public String getEmployeeid() {
        return employeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeerole.EmployeeID
     *
     * @param employeeid the value for employeerole.EmployeeID
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    public void setEmployeeid(String employeeid) {
        this.employeeid = employeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeerole.RoleID
     *
     * @return the value of employeerole.RoleID
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    public String getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeerole.RoleID
     *
     * @param roleid the value for employeerole.RoleID
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    public void setRoleid(String roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeerole
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", employeeid=").append(employeeid);
        sb.append(", roleid=").append(roleid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeerole
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Employeerole other = (Employeerole) that;
        return (this.getEmployeeid() == null ? other.getEmployeeid() == null : this.getEmployeeid().equals(other.getEmployeeid()))
            && (this.getRoleid() == null ? other.getRoleid() == null : this.getRoleid().equals(other.getRoleid()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeerole
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getEmployeeid() == null) ? 0 : getEmployeeid().hashCode());
        result = prime * result + ((getRoleid() == null) ? 0 : getRoleid().hashCode());
        return result;
    }
}