package com.uncodeframework.wms.entity;

import java.io.Serializable;

public class Employee implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.ID
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.EmployeeENL
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    private String employeeenl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.EmployeeName
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    private String employeename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.EmployeeNameLL
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    private String employeenamell;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.Email
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.Status
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.MobilePhone
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    private String mobilephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.SupervisorENL
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    private String supervisorenl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.Position
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    private String position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.TelPhone
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    private String telphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table employee
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.ID
     *
     * @return the value of employee.ID
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.ID
     *
     * @param id the value for employee.ID
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.EmployeeENL
     *
     * @return the value of employee.EmployeeENL
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    public String getEmployeeenl() {
        return employeeenl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.EmployeeENL
     *
     * @param employeeenl the value for employee.EmployeeENL
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    public void setEmployeeenl(String employeeenl) {
        this.employeeenl = employeeenl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.EmployeeName
     *
     * @return the value of employee.EmployeeName
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    public String getEmployeename() {
        return employeename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.EmployeeName
     *
     * @param employeename the value for employee.EmployeeName
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    public void setEmployeename(String employeename) {
        this.employeename = employeename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.EmployeeNameLL
     *
     * @return the value of employee.EmployeeNameLL
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    public String getEmployeenamell() {
        return employeenamell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.EmployeeNameLL
     *
     * @param employeenamell the value for employee.EmployeeNameLL
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    public void setEmployeenamell(String employeenamell) {
        this.employeenamell = employeenamell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.Email
     *
     * @return the value of employee.Email
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.Email
     *
     * @param email the value for employee.Email
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.Status
     *
     * @return the value of employee.Status
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.Status
     *
     * @param status the value for employee.Status
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.MobilePhone
     *
     * @return the value of employee.MobilePhone
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    public String getMobilephone() {
        return mobilephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.MobilePhone
     *
     * @param mobilephone the value for employee.MobilePhone
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    public void setMobilephone(String mobilephone) {
        this.mobilephone = mobilephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.SupervisorENL
     *
     * @return the value of employee.SupervisorENL
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    public String getSupervisorenl() {
        return supervisorenl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.SupervisorENL
     *
     * @param supervisorenl the value for employee.SupervisorENL
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    public void setSupervisorenl(String supervisorenl) {
        this.supervisorenl = supervisorenl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.Position
     *
     * @return the value of employee.Position
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.Position
     *
     * @param position the value for employee.Position
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    public void setPosition(String position) {
        this.position = position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.TelPhone
     *
     * @return the value of employee.TelPhone
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    public String getTelphone() {
        return telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.TelPhone
     *
     * @param telphone the value for employee.TelPhone
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    public void setTelphone(String telphone) {
        this.telphone = telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", employeeenl=").append(employeeenl);
        sb.append(", employeename=").append(employeename);
        sb.append(", employeenamell=").append(employeenamell);
        sb.append(", email=").append(email);
        sb.append(", status=").append(status);
        sb.append(", mobilephone=").append(mobilephone);
        sb.append(", supervisorenl=").append(supervisorenl);
        sb.append(", position=").append(position);
        sb.append(", telphone=").append(telphone);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Employee other = (Employee) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getEmployeeenl() == null ? other.getEmployeeenl() == null : this.getEmployeeenl().equals(other.getEmployeeenl()))
            && (this.getEmployeename() == null ? other.getEmployeename() == null : this.getEmployeename().equals(other.getEmployeename()))
            && (this.getEmployeenamell() == null ? other.getEmployeenamell() == null : this.getEmployeenamell().equals(other.getEmployeenamell()))
            && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getMobilephone() == null ? other.getMobilephone() == null : this.getMobilephone().equals(other.getMobilephone()))
            && (this.getSupervisorenl() == null ? other.getSupervisorenl() == null : this.getSupervisorenl().equals(other.getSupervisorenl()))
            && (this.getPosition() == null ? other.getPosition() == null : this.getPosition().equals(other.getPosition()))
            && (this.getTelphone() == null ? other.getTelphone() == null : this.getTelphone().equals(other.getTelphone()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getEmployeeenl() == null) ? 0 : getEmployeeenl().hashCode());
        result = prime * result + ((getEmployeename() == null) ? 0 : getEmployeename().hashCode());
        result = prime * result + ((getEmployeenamell() == null) ? 0 : getEmployeenamell().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getMobilephone() == null) ? 0 : getMobilephone().hashCode());
        result = prime * result + ((getSupervisorenl() == null) ? 0 : getSupervisorenl().hashCode());
        result = prime * result + ((getPosition() == null) ? 0 : getPosition().hashCode());
        result = prime * result + ((getTelphone() == null) ? 0 : getTelphone().hashCode());
        return result;
    }
}