package com.uncodeframework.wms.entity;

import java.io.Serializable;

public class Menurole implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menurole.MenuID
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    private String menuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menurole.RoleID
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    private String roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table menurole
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menurole.MenuID
     *
     * @return the value of menurole.MenuID
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    public String getMenuid() {
        return menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menurole.MenuID
     *
     * @param menuid the value for menurole.MenuID
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    public void setMenuid(String menuid) {
        this.menuid = menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menurole.RoleID
     *
     * @return the value of menurole.RoleID
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    public String getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menurole.RoleID
     *
     * @param roleid the value for menurole.RoleID
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    public void setRoleid(String roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menurole
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", menuid=").append(menuid);
        sb.append(", roleid=").append(roleid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menurole
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Menurole other = (Menurole) that;
        return (this.getMenuid() == null ? other.getMenuid() == null : this.getMenuid().equals(other.getMenuid()))
            && (this.getRoleid() == null ? other.getRoleid() == null : this.getRoleid().equals(other.getRoleid()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menurole
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getMenuid() == null) ? 0 : getMenuid().hashCode());
        result = prime * result + ((getRoleid() == null) ? 0 : getRoleid().hashCode());
        return result;
    }
}