package com.uncodeframework.wms.entity;

import java.io.Serializable;

public class Menu implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.ID
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.MenuName
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    private String menuname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.MenuNameEN
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    private String menunameen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.PanelName
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    private String panelname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.Position
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    private Integer position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.ParentID
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    private String parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.Status
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table menu
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.ID
     *
     * @return the value of menu.ID
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.ID
     *
     * @param id the value for menu.ID
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.MenuName
     *
     * @return the value of menu.MenuName
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    public String getMenuname() {
        return menuname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.MenuName
     *
     * @param menuname the value for menu.MenuName
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    public void setMenuname(String menuname) {
        this.menuname = menuname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.MenuNameEN
     *
     * @return the value of menu.MenuNameEN
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    public String getMenunameen() {
        return menunameen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.MenuNameEN
     *
     * @param menunameen the value for menu.MenuNameEN
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    public void setMenunameen(String menunameen) {
        this.menunameen = menunameen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.PanelName
     *
     * @return the value of menu.PanelName
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    public String getPanelname() {
        return panelname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.PanelName
     *
     * @param panelname the value for menu.PanelName
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    public void setPanelname(String panelname) {
        this.panelname = panelname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.Position
     *
     * @return the value of menu.Position
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    public Integer getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.Position
     *
     * @param position the value for menu.Position
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    public void setPosition(Integer position) {
        this.position = position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.ParentID
     *
     * @return the value of menu.ParentID
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    public String getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.ParentID
     *
     * @param parentid the value for menu.ParentID
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    public void setParentid(String parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.Status
     *
     * @return the value of menu.Status
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.Status
     *
     * @param status the value for menu.Status
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", menuname=").append(menuname);
        sb.append(", menunameen=").append(menunameen);
        sb.append(", panelname=").append(panelname);
        sb.append(", position=").append(position);
        sb.append(", parentid=").append(parentid);
        sb.append(", status=").append(status);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Menu other = (Menu) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getMenuname() == null ? other.getMenuname() == null : this.getMenuname().equals(other.getMenuname()))
            && (this.getMenunameen() == null ? other.getMenunameen() == null : this.getMenunameen().equals(other.getMenunameen()))
            && (this.getPanelname() == null ? other.getPanelname() == null : this.getPanelname().equals(other.getPanelname()))
            && (this.getPosition() == null ? other.getPosition() == null : this.getPosition().equals(other.getPosition()))
            && (this.getParentid() == null ? other.getParentid() == null : this.getParentid().equals(other.getParentid()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbggenerated Thu Dec 17 14:35:10 CST 2015
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getMenuname() == null) ? 0 : getMenuname().hashCode());
        result = prime * result + ((getMenunameen() == null) ? 0 : getMenunameen().hashCode());
        result = prime * result + ((getPanelname() == null) ? 0 : getPanelname().hashCode());
        result = prime * result + ((getPosition() == null) ? 0 : getPosition().hashCode());
        result = prime * result + ((getParentid() == null) ? 0 : getParentid().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        return result;
    }
}